services:
  - type: web
    name: manuela-ruiz-realty
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_GCServer
        value: "0"
      - key: DOTNET_EnableDiagnostics
        value: "0"
      - key: DOTNET_GCHeapHardLimit
        value: "234881024"
      - key: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
        value: "false"
      - key: ASPNETCORE_hostBuilder__reloadConfigOnChange
        value: "false"
